version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./app && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
  machine:
    image: ubuntu-2004:202010-01
  steps:
    - attach_workspace:
        at: .
    - checkout
    - run:
        name: Debugging Info
        command: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          ls -al ./app/build  # Print the contents of the local directory
          aws s3 sync ./app/build s3://cicrcleci-s3


workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test




# import boto3

# # Set up credentials
# session = boto3.Session(
#     aws_access_key_id='YOUR_ACCESS_KEY',
#     aws_secret_access_key='YOUR_SECRET_ACCESS_KEY',
#     region_name='us-east-1'
# )

# # Create client using the credentials
# s3_client = session.client('s3')

# # Use the client to interact with the service
# response = s3_client.list_buckets()
# print(response)